### ISSUE TITLE
No AC control with cloud Beko 8891973200

### ISSUE THREAD

**Issue by deceju** [rowysock/home-assistant-HomeWhiz#152]
Hello there, 
I manage to add my air conditioner to home assistant, but when I want to change settings I get an error. 
Here are the logs, is this enough to find a solution? 

2023-08-22 01:33:23.477 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547075786816] HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 617, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'
2023-08-22 01:34:54.860 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547069145792] HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 617, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'
2023-08-22 01:34:57.930 DEBUG (MainThread) [custom_components.homewhiz] Changing HVAC mode off
2023-08-22 01:34:57.931 DEBUG (MainThread) [custom_components.homewhiz] Sending command 43:20
2023-08-22 01:34:57.980 DEBUG (MainThread) [custom_components.homewhiz] Command result: {'packet_id': 37}
2023-08-22 01:35:01.915 DEBUG (MainThread) [custom_components.homewhiz] Changing fan mode WIND_STRENGTH_MID
2023-08-22 01:35:01.916 DEBUG (MainThread) [custom_components.homewhiz] Sending command 36:1
2023-08-22 01:35:01.949 DEBUG (MainThread) [custom_components.homewhiz] Command result: {'packet_id': 38}
2023-08-22 01:35:05.317 DEBUG (MainThread) [custom_components.homewhiz] Changing swing mode off
2023-08-22 01:35:05.319 DEBUG (MainThread) [custom_components.homewhiz] Sending command 38:0
2023-08-22 01:35:05.355 DEBUG (MainThread) [custom_components.homewhiz] Command result: {'packet_id': 39}
2023-08-22 01:35:11.188 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547069145792] HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 617, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'
2023-08-22 01:35:14.529 DEBUG (MainThread) [custom_components.homewhiz] Changing HVAC mode cool
2023-08-22 01:35:14.530 DEBUG (MainThread) [custom_components.homewhiz] Sending command 34:0
2023-08-22 01:35:14.598 DEBUG (MainThread) [custom_components.homewhiz] Command result: {'packet_id': 40}

**Comment by deceju** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: components/climate/__init__.py:617 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 04:41:51 (2 occurrences) 
Last logged: 04:42:00

[547400928704] HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 617, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'

**Comment by TechHummel** [comment]
Thanks for reporting this issue! 👍 
Could you please test if this issue still occurs with the latest beta release? Thanks!

**Comment by deceju** [comment]
Thank you for the answer and the work ! 
It's working well with 5.1 beta, I'm just missing the humidity sensor but otherwise it's really responsive !
